# Generated by Django 4.1.3 on 2022-11-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StreamingPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=True, verbose_name="Is Deleted"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("about", models.TextField(blank=True, verbose_name="About")),
                (
                    "website",
                    models.URLField(blank=True, max_length=100, verbose_name="Website"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=True, verbose_name="Is Deleted"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("plot", models.TextField(blank=True, verbose_name="Plot")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movies",
                        to="watchlist.streamingplatform",
                        verbose_name="Platform",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
