# Generated by Django 4.1.3 on 2022-11-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_alter_movie_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="is_deleted",
            field=models.BooleanField(default=True, verbose_name="Is Deleted"),
        ),
        migrations.AlterField(
            model_name="streamingplatform",
            name="is_deleted",
            field=models.BooleanField(default=True, verbose_name="Is Deleted"),
        ),
    ]
