# Generated by Django 4.1.3 on 2022-11-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_remove_streamingplatform_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_deleted",
        ),
    ]
