# Generated by Django 4.1.3 on 2022-11-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_alter_movie_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
