# Generated by Django 4.1.3 on 2022-11-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movies",
                to="watchlist.streamingplatform",
                verbose_name="Platform",
            ),
        ),
    ]
