# Generated by Django 4.1.3 on 2022-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0005_movie_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamingplatform",
            name="website",
            field=models.URLField(blank=True, max_length=100, verbose_name="Website"),
        ),
    ]
