# Generated by Django 4.1.3 on 2022-11-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0006_alter_streamingplatform_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_deleted",
            field=models.BooleanField(default=True, verbose_name="Is Deleted"),
        ),
    ]
